name: Build mkxp-z Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake ruby-full curl gpg

      - name: Install RVM and Ruby
        run: |
          curl -sSL https://get.rvm.io/ | bash
          source ~/.rvm/scripts/rvm
          rvm install 3.1
          rvm use 3.1 --default

      - name: Set up Android SDK and NDK
        run: |
          echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$HOME/Android/Sdk/ndk/23.2.8568313" >> $GITHUB_ENV
          echo "ARCH=linux-x86_64" >> $GITHUB_ENV
          echo "PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/$ARCH/bin:$PATH" >> $GITHUB_ENV

      - name: Install Android NDK
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;23.2.8568313"
          ls -l $ANDROID_HOME/ndk

      - name: Clone mkxp-z-android
        run: git clone https://github.com/BookerRues9/mkxp-z-android-reworked.git

      - name: Download dependencies
        run: |
          cd mkxp-z-android-reworked/app/jni
          chmod +x get_deps.sh
          ./get_deps.sh

      - name: Build for 32-bit
        run: |
          cd mkxp-z-android-reworked/app/jni
          HOST=armv7a-linux-androideabi TARGET=arm-linux-androideabi ABI=armeabi-v7a make

      - name: Build for 64-bit
        run: |
          cd mkxp-z-android-reworked/app/jni
          HOST=aarch64-linux-android TARGET=aarch64-linux-android ABI=arm64-v8a make

      - name: Compile APK
        run: |
          cd mkxp-z-android-reworked
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkxp-z-android-apk
          path: mkxp-z-android-reworked/app/build/outputs/apk/debug/*.apk
