name: Build Android Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Android SDK and NDK
        run: |
          # Crear directorio del SDK
          sudo mkdir -p /home/runner/android-sdk/cmdline-tools
          cd /home/runner/android-sdk/cmdline-tools

          # Descargar Android Command Line Tools
          sudo curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          sudo unzip sdk-tools.zip -d tools
          sudo rm sdk-tools.zip

          # Configurar rutas
          export ANDROID_HOME=/home/runner/android-sdk
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export PATH=$ANDROID_HOME/cmdline-tools/tools/bin:$PATH

          # Asegurar que sdkmanager funcione
          sdkmanager --version || echo "sdkmanager no encontrado"

          # Instalar SDK y NDK específico
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-30" "ndk;23.2.8568313"

          # Exportar variables de entorno
          echo "export ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "export ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/23.2.8568313" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/tools/bin:$PATH" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV

      - name: Verify NDK Version
        run: |
          echo "Using NDK version:"
          cat $ANDROID_NDK_HOME/source.properties


      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake ruby-full curl gpg

      - name: Install RVM and Ruby
        run: |
          sudo apt install -y gpg
          gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
          curl -sSL https://get.rvm.io | bash -s stable
          source ~/.rvm/scripts/rvm
          rvm install 3.1.5
          rvm use 3.1.5 --default
          ruby -v


      - name: Clone the repository
        run: |
          git clone https://github.com/BookerRues9/mkxp-z-android-reworked.git
          cd mkxp-z-android-reworked/app/jni
          chmod +x get_deps.sh
          ./get_deps.sh

      - name: Build JNI components
        run: |
          cd mkxp-z-android-reworked/app/jni
          make

      - name: Build APK using Gradle
        run: |
          cd mkxp-z-android-reworked
          chmod +x gradlew
          ./gradlew assembleDebug
          
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-apk
          path: mkxp-z-android-reworked/app/build/outputs/apk/debug/app-debug.apk
