name: Build mkxp-z Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake ruby-full curl unzip gpg openjdk-17-jdk

      - name: Set up Ruby
        run: |
          curl -sSL https://get.rvm.io | bash -s stable
          source ~/.rvm/scripts/rvm
          rvm install 3.1
          rvm use 3.1 --default

      - name: Set up Android SDK and NDK
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/23.2.8568313

          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip sdk-tools.zip -d latest
          rm sdk-tools.zip

          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
          echo "PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/tools/bin:$PATH" >> $GITHUB_ENV

      - name: Install Android SDK and NDK
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;23.2.8568313"

      - name: Clone mkxp-z-android
        run: git clone https://github.com/BookerRues9/mkxp-z-android-reworked.git

      - name: Download dependencies
        run: |
          cd mkxp-z-android-reworked/app/jni
          chmod +x get_deps.sh
          ./get_deps.sh

      - name: Build for 32-bit
        run: |
          cd mkxp-z-android-reworked/app/jni
          HOST=armv7a-linux-androideabi TARGET=arm-linux-androideabi ABI=armeabi-v7a make

      - name: Build for 64-bit
        run: |
          cd mkxp-z-android-reworked/app/jni
          HOST=aarch64-linux-android TARGET=aarch64-linux-android ABI=arm64-v8a make

      - name: Compile APK
        run: |
          cd mkxp-z-android-reworked
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkxp-z-android-apk
          path: mkxp-z-android-reworked/app/build/outputs/apk/debug/*.apk
