name: Build mkxp-z Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake ruby-full curl unzip gpg

      - name: Set up Ruby
        run: |
          curl -sSL https://get.rvm.io/ | bash
          source ~/.rvm/scripts/rvm
          rvm install 3.1
          rvm use 3.1 --default

      - name: Set up Android SDK and NDK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/23.2.8568313
          export ARCH=linux-x86_64
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/$ARCH/bin:$PATH" >> $GITHUB_ENV

          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -o cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest

          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --install "ndk;23.2.8568313" "platform-tools"

      - name: Verify NDK installation
        run: ls -R $ANDROID_NDK_HOME

      - name: Clone mkxp-z-android
        run: git clone https://github.com/BookerRues9/mkxp-z-android-reworked.git

      - name: Download dependencies
        run: |
          cd mkxp-z-android-reworked/app/jni
          chmod +x get_deps.sh
          ./get_deps.sh

      - name: Build for 32-bit (armeabi-v7a)
        run: |
          cd mkxp-z-android-reworked/app/jni
          HOST=armv7a-linux-androideabi TARGET=arm-linux-androideabi ABI=armeabi-v7a make

      - name: Build for 64-bit (arm64-v8a)
        run: |
          cd mkxp-z-android-reworked/app/jni
          HOST=aarch64-linux-android TARGET=aarch64-linux-android ABI=arm64-v8a make

      - name: Compile APK
        run: |
          cd mkxp-z-android-reworked
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkxp-z-android-apk
          path: mkxp-z-android-reworked/app/build/outputs/apk/debug/*.apk
