name: Build Android Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Android SDK and NDK
        run: |
          sudo apt update
          sudo apt install -y unzip wget

          # Descargar e instalar el Command Line Tools de Android
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip commandlinetools-linux-10406996_latest.zip
          mv cmdline-tools latest
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          export PATH=$ANDROID_HOME/platform-tools:$PATH

          # Aceptar licencias de Android SDK
          yes | sdkmanager --licenses

          # Instalar Android SDK y NDK 23.2.8568313
          sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34" "ndk;23.2.8568313"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake ruby-full curl gpg

      - name: Install RVM and Ruby
        run: |
          curl -sSL https://get.rvm.io | bash -s stable
          source ~/.rvm/scripts/rvm
          rvm install 3.1.5
          rvm use 3.1.5 --default
          ruby -v

      - name: Clone the repository
        run: |
          git clone https://github.com/BookerRues9/mkxp-z-android-reworked.git
          cd mkxp-z-android-reworked/app/jni
          chmod +x get_deps.sh
          ./get_deps.sh

      - name: Set environment variables
        run: |
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/23.2.8568313" >> $GITHUB_ENV
          echo "export ARCH=linux-x86_64" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/$ARCH/bin:$PATH" >> $GITHUB_ENV

      - name: Build JNI components
        run: |
          cd mkxp-z-android-reworked/app/jni
          make

      - name: Build APK using Gradle
        run: |
          cd mkxp-z-android-reworked
          chmod +x gradlew
          ./gradlew assembleDebug
          
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-apk
          path: mkxp-z-android-reworked/app/build/outputs/apk/debug/app-debug.apk
